# tanzu-java-web-app-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-java-web-app'
spec:
  type: service
  lifecycle: experimental
  system: storefrontui      # storewebapp-system.yamlのsysmte名を指定
  owner: team-storefront    # team-sf-group.yamlのgroup名を指定
