apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-storefront
  description: Team StoreFront
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-sf@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-sf@example.com.svg?background=%23fff&margin=25
  parent: e2c-dev-org
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hirokim
spec:
  profile:
    displayName: Hiroki Matsubara
    email: hiromim@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/hiromim@vmware.com.svg?background=%23fff
  memberOf: [team-storefront]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vmware-employee1
spec:
  profile:
    displayName: VMware Tanzu
    email: guest2@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest2@example.com.svg?background=%23fff
  memberOf: [team-storefront]
